### ISSUE TITLE
wikidata on sophox ?

### ISSUE THREAD

**Issue by nlehuby** [Sophox/sophox#12]
Does Sophox still contains wikidata data ?
I can't get any query working

For instance, I don't get any matches for this one :
```
SELECT * WHERE {
  ?osmId osmt:place ?place.
  ?osmId osmt:wikidata ?wd.
  ?wd wdt:P31 ?type.
}
LIMIT 10
```
https://tinyurl.com/y5so7hnh

**Comment by camelCaseNick** [comment]
RDF Linked Data for SPARQL queries aren't meant to be copied, but rather queried from all sources inside one query with a federated query.

While the sophox endpoint https://sophox.org/sparql doesn't contain any wikidata entries anymore, the wikidata endpoint https://query.wikidata.org/sparql does.

The following query to the sophox endpoint is equivalent to the original one with directly fetching from wikidata:

    select * where {
      ?osm osmt:place ?place;
           osmt:wikidata ?wd.
      service <https://query.wikidata.org/sparql> {
        ?wd wdt:P31 ?type.
      }
    }
    limit 10

**Comment by nlehuby** [comment]
Thanks for your answer.
I found this request on [Sophox documentation](https://wiki.openstreetmap.org/wiki/Sophox#Hello_.28OSM_SPARQL.29_World), under the "Hello (OSM SPARQL) World" paragraph so it may need an update.

**Comment by matkoniecz** [comment]
> Does Sophox still contains wikidata data ?

per https://wiki.openstreetmap.org/wiki/Sophox 

> Sophox no longer contains a copy of the Wikidata data due to space and performance limitations. Use federated query to call out into Wikidata's sparql endpoint.

**Comment by sfkeller** [comment]
Can someone close this issue?
