### ISSUE TITLE
Unscheduled downtime

### ISSUE THREAD

**Issue by 1ec5** [Sophox/sophox#24]
The Sophox server stopped responding a few days ago. @nyurik [tried rebooting the server](https://osmus.slack.com/archives/CEETPS4JU/p1605545142001200), but it wouldn’t come back up.

**Comment by pyrog** [comment]
Any news ?

**Comment by 1ec5** [comment]
@nyurik elaborated in [this talk list post](https://lists.openstreetmap.org/pipermail/talk/2020-December/085714.html) last week:

> The Hetzner hardware gave up, and I have to rebuild it.  Elastic (the
> company I work for) has donated their Google Cloud resources, so just need
> to spend some time on it, and see if a GCP VM would work as well as a bare
> metal box.

**Comment by arytonsenna** [comment]
> The Sophox server stopped responding a few days ago. @nyurik [tried rebooting the server](https://osmus.slack.com/archives/CEETPS4JU/p1605545142001200), but it wouldn’t come back up.

Any idea when the server will be functional again ?

**Comment by pelderson** [comment]
I use sophox queries to schedule surveys for recreational routes. I can't help you, but I wish you luck getting the server back up!

**Comment by zache-fi** [comment]
@nyurik Is there any news on Sophox revival? No matter if news are good, bad or ugly, but something would be nice to hear.

**Comment by Seandebasti** [comment]
I would like to know too, it is such a great method! I dont know how much this costs to get done, but OSMF or FOSS might help...

**Comment by nyurik** [comment]
Thanks for the ping.  Getting a second newborn really messes with one's life. Elastic has donated the hardware in GCP, and I'm working on setting it up now. No ETA yet, but hopefully soon.  Thanks for your support :)

**Comment by 1ec5** [comment]
Thanks for getting Sophox up and running again, @nyurik! 🦸 From [OSMUS Slack](https://osmus.slack.com/archives/CEETPS4JU/p1621434942000700):

> there are still some issues with the data updates, i'm working on resolving those

**Comment by 1ec5** [comment]
Sophox is fully operational, but there’s lingering data loading bug that affects the quality of results substantially: #27.

**Comment by Seandebasti** [comment]
Thanks @nyurik for the update. Unfortunately I also realized that all easy queries I succeded got less data as a result. Is there a different query rule for requesting all data from one single osm tag? thanks

**Comment by 1ec5** [comment]
The issue of incomplete results is being tracked in #27.
