### ISSUE TITLE
OSM data sync delays of a week 

### ISSUE THREAD

**Issue by arjunaraoc** [Sophox/sophox#34]
Today when I ran a query, I noticed  huge delays in syncing data from OSM.  As we are working to improve OSM , wikidata quality, this kind of delay  demotivates the users to use the  service.  Earlier I used to  get acess to the latest OSM data with  a delay of 10 to 15 minutes.   Screencast showing delay of 7 days is enclosed.
[Sophox sync delays at 06-05-24 09:59:27 AM IST.webm](https://github.com/Sophox/sophox/assets/524249/360f4102-7a34-48d0-8c98-a105c8d18d37)

**Comment by nyurik** [comment]
thanks for reporting, it has been fixed
